services:
  app:
    container_name: app
    image: app:app
    build: .
    restart: always
    environment:
      PORT: ${NODE_PORT}
    ports:
      - ${PORT}:8080
    volumes:
      - ./:/app
    networks:
      - mynet
    depends_on:
      - db
  db:
    container_name: db
    image: db:db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    build: ./database/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - mynet
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql

volumes:
  db-data:
  db-logs:

networks:
  mynet:
    driver: bridge
